# Generated by Django 4.2.4 on 2025-03-09 15:46

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name_english', models.CharField(max_length=255)),
                ('full_name_bengali', models.CharField(blank=True, max_length=255, null=True)),
                ('stage_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('primary_genre', models.CharField(choices=[('Rock', 'Rock'), ('Folk', 'Folk'), ('Pop', 'Pop'), ('Jazz', 'Jazz'), ('Classical', 'Classical')], max_length=50)),
                ('secondary_genre', models.CharField(blank=True, choices=[('Rock', 'Rock'), ('Folk', 'Folk'), ('Pop', 'Pop'), ('Jazz', 'Jazz'), ('Classical', 'Classical')], max_length=50, null=True)),
                ('performance_languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True, null=True)),
                ('social_links', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None)),
                ('bio', models.TextField(blank=True, max_length=1000, null=True)),
                ('portfolio_description', models.TextField(blank=True, null=True)),
                ('credits', models.CharField(blank=True, max_length=255, null=True)),
                ('content_links', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None)),
                ('content_uploads', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None)),
                ('instruments', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('technical_preferences', models.TextField(blank=True, null=True)),
                ('available_from_times', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), blank=True, null=True, size=None)),
                ('available_to_times', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), blank=True, null=True, size=None)),
                ('available_from_dates', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, null=True, size=None)),
                ('available_to_dates', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, null=True, size=None)),
                ('government_id_upload', models.URLField(blank=True, null=True)),
                ('consent_promotion', models.BooleanField(default=False)),
                ('agree_terms', models.BooleanField(default=False)),
                ('preferred_payment_method', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
