# Generated by Django 4.2.4 on 2025-03-19 11:03

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmMaker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('basic_info', models.JSONField(blank=True, null=True)),
                ('project_info', models.JSONField(blank=True, null=True)),
                ('primary_contact_info', models.JSONField(blank=True, null=True)),
                ('brief_synopsis', models.TextField(blank=True, null=True)),
                ('production_overview', models.JSONField(blank=True, null=True)),
                ('budget_breakdown', models.JSONField(blank=True, null=True)),
                ('payment_terms', models.JSONField(blank=True, null=True)),
                ('additional_details', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='artist',
            name='available_from_dates',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='available_from_times',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='available_to_dates',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='available_to_times',
        ),
        migrations.AddField(
            model_name='artist',
            name='available_timelines',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='artist',
            name='agree_terms',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='consent_promotion',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='full_name_english',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='primary_genre',
            field=models.CharField(blank=True, choices=[('Rock', 'Rock'), ('Folk', 'Folk'), ('Pop', 'Pop'), ('Jazz', 'Jazz'), ('Classical', 'Classical'), ('Hip-Hop', 'Hip-Hop')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='secondary_genre',
            field=models.CharField(blank=True, choices=[('Rock', 'Rock'), ('Folk', 'Folk'), ('Pop', 'Pop'), ('Jazz', 'Jazz'), ('Classical', 'Classical'), ('Hip-Hop', 'Hip-Hop')], max_length=50, null=True),
        ),
    ]
